on:
  push:
    branches:
    - 1.16.5
jobs:
  build_mod:
    runs-on: ubuntu-latest
    steps:
      - uses: Kir-Antipov/mc-publish@v2.0
        with:
          modrinth-id: gokistats
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 298141
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
