on:
  push:
    branches:
    - 1.16.5
jobs:
  build_mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build artifacts
        run: ./gradlew clean build
      - uses: Kir-Antipov/mc-publish@v2.0
        with:
          curseforge-id: 298141
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar
          loaders: |
            forge
          game-versions: |
            1.16.5
          version-type: beta
          java: |
            8
